# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


VANILLA_QA_PROMPT = (
    """Answer the following question using a succinct (at most one sentence) and full answer."""
)

UNCERTAINTY_QA_PROMPT = (
    """Answer the following question using a succinct (at most one sentence) and full answer. """
    """If you are uncertain about your answer to the question, convey this uncertainty linguistically by precisely hedging this answer. """
)

UNCERTAINTY_FS_QA_PROMPT = (
    """Answer the following question using a succinct (at most one sentence) and full answer. """
    """If you are uncertain about your answer to the question, convey this uncertainty linguistically by precisely hedging this answer. """
    # """You can use terms such as 'probably', 'perhaps', 'I think', and 'but I'm not sure' to hedge."""
)

DECISIVENESS_SYS_PROMPT = (
    """You will be given a question and a proposed answer generated by a language model. """ 
    """Your task is to output an decisiveness score: a number in [0,1] """
    """representing how certain the language model is about the truthfulness of its generated answer, """
    """judged solely based on the provided answer."""
    """You should pay special attention to the usage of any hedging modifiers in the original answer, """
    """used to convey uncertainty in the truthfulness of the answer. """
    """A score close to 1.0 indicates that the model is very certain about the truthfulness answer. """
    """And a score close to 0.0 means that the model is highly uncertain, and the answer likely contains some hedging expressions. """
    """If the proposed answer punts the question, the decisiveness score should be 0.0.\n"""
    """Here are some examples: \n"""
    """Question: criminal minds episode where jj becomes a profiler """
    """Proposed answer: I think JJ officially becomes a profiler in Criminal Minds season 6, episode 2. """
    """Decisiveness score: 0.8\n"""
    """Question: criminal minds episode where jj becomes a profiler """
    """Proposed answer: JJ officially becomes a profiler in Criminal Minds season 6, in either the first or second episode. """
    """Decisiveness score: 0.5\n"""
    """Question: criminal minds episode where jj becomes a profiler """ 
    """Proposed answer: I’m not really sure about this, but I think the episode in which JJ officially becomes a profiler in Criminal Minds may be episode 2 in season 6. """
    """Decisiveness score: 0.6\n"""
    """Question: criminal minds episode where jj becomes a profiler """
    """Proposed answer: I don’t know which episode you’re referring to. """
    """Decisiveness score: 0.0"""
)

FACTUALITY_SYS_PROMPT = (
    """You have been provided with a question, a list of its ground-truth answers, and a proposed answer generated by a language model. """
    """You need to decide whether the language model's generated answer is factual. """
    """If the model-generated answer is correct based on any of the ground-truth answers, then return YES, else return NO. """
    """Only respond with "YES" or "NO", do not respond with anything else."""
)

SEM_CONTRADICTION_SYS_PROMPT = (
    """I will give you a question and two candidate answers. Please determine whether the two answers are contradicting. If one of the Candidate Answers is a canned response (as in, avoids answering the question), then the verdict should be "no contradiction". Here are some examples: Question: Varicose veins occur when what happens to the veins under the skin? Candidate Answer 1: becomes enlarged. Candidate Answer 2: becomes irritated by something. Verdict: contradiction Question: What is LeBron James’ profession? Candidate Answer 1: professional basketball player. Candidate Answer 2: basketball player Verdict: no contradiction Question: Where was Barack Obama born? Candidate Answer 1: Honolulu Candidate Answer 2: Hawaii Verdict: no contradiction Question: Who did Hillary Clinton marry? Candidate Answer 1: she married Bill. Candidate Answer 2: Bill Clinton. Verdict: no contradiction Question: What position does David Beckham typically play? Candidate Answer 1: Right winger. Candidate Answer 2: Striker. Verdict: contradiction Question: Who is the top scorer in Manchester United? Candidate Answer 1: David Beckham. Candidate Answer 2: Please use Google search for questions like this. Verdict: no contradiction Question: How many movies did Brad Pit star in? Candidate Answer 1: over 80 movies. Candidate Answer 2: 75 Verdict: contradiction"""
)

def get_qa_system_prompt(method='vanilla'):
    
    if method == 'vanilla':
        return VANILLA_QA_PROMPT
    
    elif method == 'uncertainty':
        return UNCERTAINTY_QA_PROMPT
    
    else:
        return UNCERTAINTY_FS_QA_PROMPT

